### ISSUE TITLE
Import Error after building

### ISSUE THREAD

**Issue by mitch-galea** [teboli/chromatic_aberration_filtering#1]
Hello,

Really interested in this application, and nice online demo! Trying to build this on my ubuntu 20.04 machine. After runnings compile_cython.sh and opening a python terminal to import I get the following error:
```
>>> import chromatic_aberration_filtering
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mga/src/local/chromatic_aberration_filtering/chromatic_aberration_filtering/__init__.py", line 1, in <module>
    from .filter_cython import chromatic_removal
ModuleNotFoundError: No module named 'chromatic_aberration_filtering.filter_cython'
```
Any help would be appreciated, cheers

**Comment by teboli** [comment]
Hi, thanks for your interest. Did you raise the error by running the main.py file or importing the package in you own code? 

What you could try first is to install the code with 
python setup.py install

Let me know if it works. Otherwise I will have a look at the imports.

Best,

Thomas
